Fix everything
kashav/kashav.github.io pull request #1
Opened 2020-10-08 22:52 UTC by Ben-Wu

2020-10-09 00:23 UTC, imjching approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :)

2020-10-13 19:04 UTC, kashav requested changes

2020-10-13 19:04 UTC, kashav commented on index.html
> +    <div class="main-container">
I'm trying to keep the environmental footprint of this project as low as possible, so I'd really prefer if we didn't introduce a separate class for this. It's the only `<div>` in the file, we can just select it directly with `div`.

2020-10-13 19:04 UTC, kashav commented on index.html
> +      }
I **hate** giving css curlies their own line. Please change this.

2020-10-13 19:08 UTC, BenWu commented
ℐ 𝒹𝒾𝓈𝒶𝓰𝓇ℯℯ 𝚭𝚯𝚯𝚸

2020-10-13 19:08 UTC, closed without merging